@startuml
class ConsoleSizeChecker {
    <<const>> - consoleWindowTooSmallErrorMessage : string = "Please resize the console window to fit the suggestion buffer."
    - consoleTooSmallErrorMessageDisplayed : bool
    - errorMessageStartLeft : int
    - errorMessageStartTop : int
    + ShowConsoleTooSmallError() : void
    + HideConsoleTooSmallError() : void
    + IsConsoleWindowTooSmall(suggestionWindowHeight:int) : bool
    + IsErrorMessageDisplayed() : bool
}
@enduml
