@startuml
abstract class PersistenceException {
    # PersistenceException(message:string)
    # PersistenceException(message:string, innerException:Exception)
}
Exception <|-- PersistenceException
@enduml
