@startuml
class DictionaryLoader {
    + DictionaryLoader(persistenceService:IPersistenceService)
    + Load(filepath:FilePath) : WordTree
}
IDictionaryLoader <|-- DictionaryLoader
DictionaryLoader --> "persistenceService" IPersistenceService
@enduml
