@startuml
class DuplicateAlphabetCharacterException <<sealed>> {
    + DuplicateAlphabetCharacterException()
    + DuplicateAlphabetCharacterException(duplicateChar:char)
}
SpellCheckingToolException <|-- DuplicateAlphabetCharacterException
@enduml
