@startuml
class InvalidWordException <<sealed>> {
    + InvalidWordException(message:string)
    + InvalidWordException(message:string, innerException:Exception)
}
SpellCheckingToolException <|-- InvalidWordException
@enduml
