@startuml
class InvalidWordCharacterException <<sealed>> {
    + InvalidWordCharacterException()
    + InvalidWordCharacterException(word:string)
}
SpellCheckingToolException <|-- InvalidWordCharacterException
@enduml
