@startuml
class InvalidSerializedAlphabetException <<sealed>> {
    + InvalidSerializedAlphabetException()
    + InvalidSerializedAlphabetException(message:string)
}
SpellCheckingToolException <|-- InvalidSerializedAlphabetException
@enduml
