@startuml
class PersonalDictionaryWordNotFoundException <<sealed>> {
    + PersonalDictionaryWordNotFoundException(word:string)
}
SpellCheckingToolException <|-- PersonalDictionaryWordNotFoundException
@enduml
