@startuml
class UserNotFoundDomainException <<sealed>> {
    + UserNotFoundDomainException(userId:Guid)
    + UserNotFoundDomainException(username:string)
}
SpellCheckingToolException <|-- UserNotFoundDomainException
@enduml
