@startuml
class Server {
    - isRequestLoopRunning : bool
    + IsStarted : bool <<get>>
    + Server()
    + Start(port:int) : void
    + Stop() : void
    + Use(middleware:Middleware) : void
    - HandleRequests() : void
}
Server --> "listener" HttpListener
Server --> "middlewares" MiddlewarePipeline
Server --> "router" Router
Server --> "requestThread" Thread
@enduml
