@startuml
abstract class ExecutableParser {
    + {abstract} GetAllShellExecutables() : WordTree
    # InvokeShellCommand(shellName:string, arguments:string, workingDir:string) : List<string>
}
IExecutableParser <|-- ExecutableParser
@enduml
